/******************************************************************************
*  Generated by PSoC Designer 5.1.2101.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "LCD_1.h"

#endif
